import React, { useCallback, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Share,
  ScrollView,
  TextInput,
  Modal,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { apiGet, apiPost, apiDelete } from '../api/client';
import { FontFamily } from '../theme/fonts';
import { Type, typeLh } from '../theme/typography';

const VIOLET = '#5E35B1';
const DEEP = '#0D0D0D';

function formatEarnings(cents) {
  return `€${(Number(cents || 0) / 100).toFixed(2)}`;
}

function buildReportHtml(report) {
  const from = new Date(report.from);
  const to = new Date(report.to);
  const fmtDate = (d) => d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const totalEarnings = report.affiliates.reduce((s, a) => s + Number(a.week_earnings_cents || 0), 0);
  const totalSubs = report.affiliates.reduce((s, a) => s + Number(a.week_new_subscribers || 0), 0);

  const rows = report.affiliates.map((a) => `
    <tr>
      <td>${a.influencer_name || '—'}</td>
      <td style="font-family:monospace;letter-spacing:2px;color:#5E35B1">${a.affiliate_code}</td>
      <td style="text-align:center">${a.week_new_referrals ?? 0}</td>
      <td style="text-align:center">${a.week_new_subscribers ?? 0}</td>
      <td style="text-align:right;color:#5E35B1;font-weight:600">${formatEarnings(a.week_earnings_cents)}</td>
      <td style="text-align:right;color:#888">${formatEarnings(a.total_earnings_cents)}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <style>
    body{font-family:-apple-system,Helvetica,Arial,sans-serif;margin:0;padding:32px;color:#0D0D0D;font-size:14px}
    h1{font-size:22px;margin:0 0 4px}
    .sub{color:#888;font-size:13px;margin-bottom:28px}
    table{width:100%;border-collapse:collapse;margin-top:8px}
    th{background:#5E35B1;color:#fff;padding:10px 12px;text-align:left;font-size:12px;letter-spacing:.5px}
    th:nth-child(3),th:nth-child(4){text-align:center}
    th:nth-child(5),th:nth-child(6){text-align:right}
    td{padding:10px 12px;border-bottom:1px solid #eee;font-size:13px}
    tr:last-child td{border-bottom:none}
    .summary{margin-top:24px;background:#FFFFFF;border-radius:12px;padding:16px 20px;display:flex;gap:32px}
    .s-item{display:flex;flex-direction:column}
    .s-val{font-size:22px;font-weight:700;color:#5E35B1}
    .s-lbl{font-size:11px;color:#888;margin-top:2px;text-transform:uppercase;letter-spacing:.5px}
    .footer{margin-top:32px;font-size:11px;color:#aaa;text-align:center}
  </style></head><body>
  <h1>ColorBar Suite — Partner Report</h1>
  <div class="sub">${fmtDate(from)} – ${fmtDate(to)}</div>
  <table>
    <thead><tr>
      <th>Influencer</th><th>Code</th>
      <th>New referrals</th><th>New subscribers</th>
      <th>This week</th><th>All time</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="summary">
    <div class="s-item"><span class="s-val">${totalSubs}</span><span class="s-lbl">New subscribers</span></div>
    <div class="s-item"><span class="s-val">${formatEarnings(totalEarnings)}</span><span class="s-lbl">Commissions this week</span></div>
    <div class="s-item"><span class="s-val">${report.affiliates.length}</span><span class="s-lbl">Active partners</span></div>
  </div>
  <div class="footer">Generated by ColorBar Suite · ${new Date().toLocaleString('en-GB')}</div>
  </body></html>`;
}

function AffiliateRow({ item, onShare, onDelete }) {
  return (
    <View style={styles.row}>
      <View style={styles.rowLeft}>
        <Text style={styles.rowName} numberOfLines={1}>{item.influencer_name || '—'}</Text>
        <View style={styles.codePill}>
          <Text style={styles.codePillText}>{item.affiliate_code}</Text>
        </View>
        <Text style={styles.rowStats}>
          {item.active_referrals ?? 0} active · {formatEarnings(item.total_earnings_cents)} earned
        </Text>
      </View>
      <View style={styles.rowActions}>
        <TouchableOpacity style={styles.iconBtn} onPress={() => onShare(item)} hitSlop={8}>
          <Ionicons name="share-outline" size={20} color={VIOLET} />
        </TouchableOpacity>
        <TouchableOpacity style={styles.iconBtn} onPress={() => onDelete(item)} hitSlop={8}>
          <Ionicons name="trash-outline" size={20} color="#C62828" />
        </TouchableOpacity>
      </View>
    </View>
  );
}

export default function AffiliateScreen() {
  const navigation = useNavigation();
  const insets = useSafeAreaInsets();
  const [loading, setLoading] = useState(true);
  const [affiliates, setAffiliates] = useState([]);
  const [modalVisible, setModalVisible] = useState(false);
  const [nameDraft, setNameDraft] = useState('');
  const [creating, setCreating] = useState(false);
  const [generatingReport, setGeneratingReport] = useState(false);

  const load = useCallback(async () => {
    try {
      setLoading(true);
      const data = await apiGet('/api/affiliates', { allowStaleCache: false });
      setAffiliates(Array.isArray(data) ? data : []);
    } catch (e) {
      Alert.alert('', String(e?.message || 'Could not load affiliates.'));
    } finally {
      setLoading(false);
    }
  }, []);

  useFocusEffect(useCallback(() => { load(); }, [load]));

  const openAdd = () => {
    setNameDraft('');
    setModalVisible(true);
  };

  const createAffiliate = async () => {
    const name = nameDraft.trim();
    if (!name) {
      Alert.alert('', 'Enter the influencer name.');
      return;
    }
    setCreating(true);
    try {
      const item = await apiPost('/api/affiliates', { influencer_name: name });
      setAffiliates((prev) => [item, ...prev]);
      setModalVisible(false);
    } catch (e) {
      Alert.alert('', String(e?.message || 'Could not create affiliate.'));
    } finally {
      setCreating(false);
    }
  };

  const shareAffiliate = async (item) => {
    const deepLink = `colorbar-suite://join?ref=${item.affiliate_code}`;
    try {
      await Share.share({
        message: `Try ColorBar Suite!\nUse ${item.influencer_name}'s link:\n${deepLink}\nOr enter code: ${item.affiliate_code}`,
        url: deepLink,
      });
    } catch {
      // dismissed
    }
  };

  const deleteAffiliate = (item) => {
    Alert.alert(
      'Remove affiliate',
      `Remove code for ${item.influencer_name}? This cannot be undone.`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Remove',
          style: 'destructive',
          onPress: async () => {
            try {
              await apiDelete(`/api/affiliates/${item.id}`);
              setAffiliates((prev) => prev.filter((a) => a.id !== item.id));
            } catch (e) {
              Alert.alert('', String(e?.message || 'Could not remove.'));
            }
          },
        },
      ],
    );
  };

  const generateWeeklyReport = async () => {
    if (generatingReport) return;
    setGeneratingReport(true);
    try {
      const report = await apiGet('/api/affiliates/report', { allowStaleCache: false });
      const html = buildReportHtml(report);
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Weekly Partner Report' });
    } catch (e) {
      Alert.alert('', String(e?.message || 'Could not generate report.'));
    } finally {
      setGeneratingReport(false);
    }
  };

  const totalEarnings = affiliates.reduce((s, a) => s + Number(a.total_earnings_cents || 0), 0);
  const totalActive = affiliates.reduce((s, a) => s + Number(a.active_referrals || 0), 0);

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'left', 'right']}>
      <View style={styles.topBar}>
        <TouchableOpacity hitSlop={12} onPress={() => navigation.goBack()} accessibilityRole="button">
          <Ionicons name="chevron-back" size={26} color={DEEP} />
        </TouchableOpacity>
        <Text style={styles.topTitle}>Partner Program</Text>
        <TouchableOpacity hitSlop={12} onPress={openAdd} accessibilityRole="button">
          <Ionicons name="add" size={28} color={VIOLET} />
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.center}>
          <ActivityIndicator color={DEEP} />
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={[styles.scroll, { paddingBottom: Math.max(insets.bottom, 32) }]}
          showsVerticalScrollIndicator={false}
        >
          {affiliates.length > 0 && (
            <TouchableOpacity
              style={[styles.reportBtn, generatingReport && { opacity: 0.55 }]}
              onPress={generateWeeklyReport}
              disabled={generatingReport}
              activeOpacity={0.88}
            >
              {generatingReport
                ? <ActivityIndicator color={VIOLET} size="small" />
                : <Ionicons name="document-text-outline" size={18} color={VIOLET} style={{ marginRight: 8 }} />
              }
              <Text style={styles.reportBtnText}>
                {generatingReport ? 'Generating…' : 'Weekly Report PDF'}
              </Text>
            </TouchableOpacity>
          )}

          {affiliates.length > 0 && (
            <View style={styles.summaryRow}>
              <View style={styles.summaryCard}>
                <Text style={styles.summaryValue}>{affiliates.length}</Text>
                <Text style={styles.summaryLabel}>Influencers</Text>
              </View>
              <View style={styles.summaryCard}>
                <Text style={styles.summaryValue}>{totalActive}</Text>
                <Text style={styles.summaryLabel}>Active subs</Text>
              </View>
              <View style={styles.summaryCard}>
                <Text style={[styles.summaryValue, { color: VIOLET }]}>{formatEarnings(totalEarnings)}</Text>
                <Text style={styles.summaryLabel}>Total earned</Text>
              </View>
            </View>
          )}

          {affiliates.length === 0 ? (
            <View style={styles.emptyState}>
              <Ionicons name="people-outline" size={52} color="#AEAEB2" />
              <Text style={styles.emptyTitle}>No influencers yet</Text>
              <Text style={styles.emptyBody}>
                Tap + to add your first influencer and generate a unique referral code for them.
              </Text>
              <TouchableOpacity style={styles.addBtn} onPress={openAdd} activeOpacity={0.88}>
                <Text style={styles.addBtnText}>Add influencer</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <>
              <Text style={styles.sectionLabel}>INFLUENCERS</Text>
              {affiliates.map((item) => (
                <AffiliateRow
                  key={item.id}
                  item={item}
                  onShare={shareAffiliate}
                  onDelete={deleteAffiliate}
                />
              ))}
            </>
          )}

          <View style={styles.infoBox}>
            <Ionicons name="information-circle-outline" size={18} color={VIOLET} style={{ marginRight: 8, marginTop: 1 }} />
            <Text style={styles.infoText}>
              Each influencer gets a unique code. They earn 20% of every subscription purchased via their link.
            </Text>
          </View>
        </ScrollView>
      )}

      <Modal visible={modalVisible} transparent animationType="slide">
        <KeyboardAvoidingView
          style={{ flex: 1 }}
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        >
        <View style={styles.modalOverlay}>
          <View style={[styles.modalCard, { paddingBottom: Math.max(insets.bottom, 24) }]}>
            <Text style={styles.modalTitle}>New influencer</Text>
            <Text style={styles.modalHint}>Enter the influencer's name to generate their code.</Text>
            <TextInput
              style={styles.modalInput}
              value={nameDraft}
              onChangeText={setNameDraft}
              placeholder="e.g. Maria_Style"
              placeholderTextColor="#AEAEB2"
              autoCapitalize="words"
              autoFocus
              returnKeyType="done"
              onSubmitEditing={createAffiliate}
            />
            <TouchableOpacity
              style={[styles.addBtn, creating && { opacity: 0.55 }]}
              onPress={createAffiliate}
              disabled={creating}
              activeOpacity={0.88}
            >
              {creating
                ? <ActivityIndicator color="#FFFFFF" />
                : <Text style={styles.addBtnText}>Generate code</Text>
              }
            </TouchableOpacity>
            <TouchableOpacity style={styles.cancelBtn} onPress={() => setModalVisible(false)}>
              <Text style={styles.cancelBtnText}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </View>
        </KeyboardAvoidingView>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FFFFFF' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  topTitle: { ...Type.screenTitle, color: DEEP },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scroll: { paddingHorizontal: 20, paddingTop: 4 },

  summaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  summaryCard: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#E5E5EA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryValue: {
    fontFamily: FontFamily.semibold,
    fontSize: 22,
    lineHeight: typeLh(22),
    color: DEEP,
  },
  summaryLabel: { ...Type.secondary, marginTop: 3 },

  sectionLabel: {
    ...Type.sectionLabel,
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#E5E5EA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  rowLeft: { flex: 1 },
  rowName: {
    fontFamily: FontFamily.semibold,
    fontSize: 15,
    lineHeight: typeLh(15),
    color: DEEP,
    marginBottom: 6,
  },
  codePill: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 6,
  },
  codePillText: {
    fontFamily: FontFamily.bold,
    fontSize: 13,
    letterSpacing: 2,
    color: VIOLET,
  },
  rowStats: { ...Type.secondary },
  rowActions: { flexDirection: 'row', gap: 4 },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },

  emptyState: { marginTop: 48, alignItems: 'center', paddingHorizontal: 8 },
  emptyTitle: { marginTop: 16, marginBottom: 8, ...Type.screenTitle, textAlign: 'center' },
  emptyBody: { ...Type.secondary, textAlign: 'center', marginBottom: 28, lineHeight: typeLh(14) },

  addBtn: {
    alignSelf: 'stretch',
    backgroundColor: DEEP,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtnText: { ...Type.buttonLabel, color: '#FFFFFF' },

  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginTop: 16,
  },
  infoText: {
    flex: 1,
    fontFamily: FontFamily.regular,
    fontSize: 13,
    lineHeight: typeLh(13),
    color: VIOLET,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
  },
  modalTitle: { ...Type.screenTitle, marginBottom: 6 },
  modalHint: { ...Type.secondary, marginBottom: 16 },
  modalInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#E5E5EA',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: FontFamily.regular,
    color: DEEP,
    marginBottom: 14,
  },
  cancelBtn: { marginTop: 10, alignItems: 'center', paddingVertical: 10 },
  cancelBtnText: { ...Type.buttonLabel, color: '#AEAEB2' },
  reportBtn: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: VIOLET,
    borderRadius: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  reportBtnText: { ...Type.buttonLabel, color: VIOLET },
});
